version: '3.8'

services:
  web:
    build: .
    ports:
      - "5005:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/myDatabase
      - MONGO_DB_NAME=myDatabase
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
